services:
  - postgresql
  before_script:
    - "psql -c 'CREATE DATABASE task_test;' -U postgres"
    - "bundle exec rails db:migrate"
    #- psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres 
  language: ruby
  rvm:
    -2.5.1
  script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec