addons:
  postgresql: 9.6
  before_script:
    - psql -c "CREATE DATABASE testing_db;" -U postgres
    - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres 
  language: ruby
  rvm:
    -2.5.1
  script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec